package net.ghoula.eru.http

import java.security.MessageDigest

import net.ghoula.eru.*

/** HTTP ETag (Entity Tag) as defined in RFC 9110 Section 8.8.3.
  *
  * ETags are validators that enable efficient caching and conditional requests. They can be either
  * strong (exact match required) or weak (semantic equivalence).
  *
  * @param value
  *   the ETag value (without quotes or W/ prefix)
  * @param weak
  *   true if this is a weak ETag, false for strong
  *
  * @see
  *   [[https://www.rfc-editor.org/rfc/rfc9110.html#section-8.8.3 RFC 9110 Section 8.8.3 - ETag]]
  */
final case class ETag(
  value: String,
  weak: Boolean = false
) {

  /** Serializes this ETag to its header value format.
    *
    * Strong ETags are quoted: "abc123" Weak ETags have W/ prefix: W/"abc123"
    *
    * @return
    *   the ETag header value
    */
  def headerValue: String = {
    if weak then s"""W/"$value""""
    else s""""$value""""
  }

  /** Checks if this ETag matches another ETag.
    *
    * Per RFC 9110:
    *   - Strong ETags match only if both are strong and have identical values
    *   - Weak ETags match if both have identical values (regardless of strength)
    *
    * @param other
    *   the ETag to compare against
    * @param strongComparison
    *   if true, use strong comparison semantics
    * @return
    *   true if the ETags match
    */
  def matches(other: ETag, strongComparison: Boolean = false): Boolean = {
    if strongComparison then {
      // Strong comparison: both must be strong and values must match
      !this.weak && !other.weak && this.value == other.value
    } else {
      // Weak comparison: values must match (ignore weak flag)
      this.value == other.value
    }
  }

  /** Checks if this ETag matches any ETag in a list.
    *
    * @param others
    *   the list of ETags to check against
    * @param strongComparison
    *   if true, use strong comparison semantics
    * @return
    *   true if this ETag matches any in the list
    */
  def matchesAny(others: List[ETag], strongComparison: Boolean = false): Boolean = {
    others.exists(matches(_, strongComparison))
  }
}

object ETag {

  /** Parses an ETag from a header value.
    *
    * Accepts formats:
    *   - Strong: "abc123"
    *   - Weak: W/"abc123"
    *
    * @param value
    *   the ETag header value
    * @return
    *   the parsed ETag or a ParseError
    */
  def parse(value: String): Eru[ParseError, ETag] = {
    val trimmed = value.trim

    if trimmed.isEmpty then {
      Eru.fail(ParseError(value, "ETag cannot be empty"))
    } else {
      // Check for weak ETag
      val (weak, rest) = if trimmed.startsWith("W/") || trimmed.startsWith("w/") then {
        (true, trimmed.substring(2).trim)
      } else {
        (false, trimmed)
      }

      // Extract quoted value
      if rest.startsWith("\"") && rest.endsWith("\"") && rest.length >= 2 then {
        val etagValue = rest.substring(1, rest.length - 1)
        if isValidETagValue(etagValue) then {
          Eru.succeed(ETag(etagValue, weak))
        } else {
          Eru.fail(ParseError(value, "ETag value contains invalid characters"))
        }
      } else {
        Eru.fail(ParseError(value, "ETag must be quoted"))
      }
    }
  }

  /** Parses multiple ETags from a header value (e.g., If-None-Match).
    *
    * Handles comma-separated list of ETags and the special "*" value.
    *
    * @param value
    *   the header value containing multiple ETags
    * @return
    *   the list of parsed ETags or a ParseError
    */
  def parseMultiple(value: String): Eru[ParseError, List[ETag]] = {
    val trimmed = value.trim

    // Handle special "*" case (matches anything)
    if trimmed == "*" then {
      Eru.succeed(List.empty) // Empty list represents "match all"
    } else {
      // Split by comma and parse each ETag
      val parts = splitETags(trimmed)
      if parts.isEmpty then {
        Eru.succeed(List.empty)
      } else {
        val parsed = parts.map(parse)
        // Sequence all results - fails fast on first error
        Eru.foreach(parsed)(identity)
      }
    }
  }

  /** Creates a strong ETag from a value.
    *
    * @param value
    *   the ETag value (will be quoted in header)
    * @return
    *   a strong ETag
    */
  def strong(value: String): ETag = ETag(value, weak = false)

  /** Creates a weak ETag from a value.
    *
    * @param value
    *   the ETag value (will be quoted with W/ prefix in header)
    * @return
    *   a weak ETag
    */
  def weak(value: String): ETag = ETag(value, weak = true)

  /** Generates a strong ETag from body content using SHA-256 hash.
    *
    * This provides a cryptographically strong validator for the content. The ETag is generated by:
    *   1. Converting the body to bytes
    *   1. Computing SHA-256 hash of the bytes
    *   1. Encoding the hash as hex string
    *
    * @param body
    *   the body to generate an ETag for
    * @return
    *   an Eru effect producing the generated ETag or an error
    */
  def fromContent(body: Body): Eru[HttpError, ETag] = {
    body match {
      case Body.Empty =>
        // Empty body gets a consistent ETag
        Eru.succeed(strong("0"))

      case Body.Text(value, _, charset) =>
        val bytes = Bytes.fromString(value, charset)
        Eru.succeed(fromBytes(bytes))

      case Body.Binary(bytes, _) =>
        Eru.succeed(fromBytes(bytes))

      case stream: Body.Stream =>
        // For streams, we need to consume the content
        stream.toBytes
          .map(fromBytes)
          .mapError(_ => HttpError.BodyEncodeError(EncodeError("Failed to generate ETag from stream")))
    }
  }

  /** Generates a strong ETag from bytes using SHA-256 hash.
    *
    * @param bytes
    *   the bytes to hash
    * @return
    *   a strong ETag with hex-encoded SHA-256 hash
    */
  def fromBytes(bytes: Bytes): ETag = {
    val digest = MessageDigest.getInstance("SHA-256")
    val hash = digest.digest(bytes.toArray)
    val hexHash = hash.map("%02x".format(_)).mkString
    strong(hexHash)
  }

  /** Generates a weak ETag from body content.
    *
    * Uses the same hashing approach as fromContent but produces a weak ETag.
    *
    * @param body
    *   the body to generate an ETag for
    * @return
    *   an Eru effect producing the generated weak ETag or an error
    */
  def fromContentWeak(body: Body): Eru[HttpError, ETag] = {
    fromContent(body).map(etag => weak(etag.value))
  }

  // Validation

  /** Validates an ETag value according to RFC 9110.
    *
    * @param s
    *   the value to validate
    * @return
    *   true if the value is valid for use in an ETag
    */
  private def isValidETagValue(s: String): Boolean = {
    // ETag value can contain any visible characters (VCHAR) or obs-text except quotes
    // VCHAR includes 0x21-0x7E which includes space-like characters
    // We allow everything except control characters and unescaped quotes
    s.forall { c =>
      (c >= 0x21 && c <= 0x7e && c != '"') || // Printable ASCII except quote
      c == 0x20 || // Space (SP)
      c >= 0x80 // obs-text (extended ASCII)
    }
  }

  /** Splits a comma-separated list of ETags, respecting quoted strings.
    *
    * @param value
    *   the string containing multiple ETags
    * @return
    *   the list of individual ETag strings
    */
  private def splitETags(value: String): List[String] = {
    // Split by comma, but be careful not to split inside quoted strings
    val result = scala.collection.mutable.ListBuffer[String]()
    val current = new StringBuilder
    var inQuotes = false
    var i = 0

    while i < value.length do {
      val c = value.charAt(i)
      c match {
        case '"' =>
          inQuotes = !inQuotes
          current.append(c)
        case ',' if !inQuotes =>
          val part = current.toString.trim
          if part.nonEmpty then result += part
          current.clear()
        case _ =>
          current.append(c)
      }
      i += 1
    }

    // Add last part
    val part = current.toString.trim
    if part.nonEmpty then result += part

    result.toList
  }
}
