#!/bin/bash
# HPACK Test Vectors Runner
# Downloads and validates against official HPACK test vectors from http2jp
#
# Test vectors source: https://github.com/http2jp/hpack-test-case
# These vectors are generated by multiple HTTP/2 implementations and
# provide interoperability validation.

set -e

VECTORS_DIR="/tmp/hpack-test-case"
VECTORS_REPO="https://github.com/http2jp/hpack-test-case.git"

echo "========================================"
echo "HPACK Test Vectors Validation"
echo "========================================"
echo ""

# Download test vectors if not present
if [ ! -d "$VECTORS_DIR" ]; then
    echo "Downloading HPACK test vectors..."
    git clone --depth 1 "$VECTORS_REPO" "$VECTORS_DIR"
    echo ""
else
    echo "Using cached test vectors at $VECTORS_DIR"
    echo "(delete $VECTORS_DIR to re-download)"
    echo ""
fi

# List available test suites
echo "Available test suites (from various HTTP/2 implementations):"
echo ""
ls -1 "$VECTORS_DIR" | grep -v -E "^(README|\.)" | while read dir; do
    count=$(ls -1 "$VECTORS_DIR/$dir"/*.json 2>/dev/null | wc -l)
    if [ "$count" -gt 0 ]; then
        echo "  - $dir: $count test files"
    fi
done

echo ""
echo "========================================"
echo "Test Vector Format"
echo "========================================"
echo ""
echo "Each test file contains sequences of:"
echo "  1. Input headers (name/value pairs)"
echo "  2. Expected wire format (hex-encoded bytes)"
echo "  3. Expected dynamic table state after encoding"
echo ""
echo "To validate our HPACK implementation, run the Scala test suite:"
echo ""
echo "  sbt 'coreJVM/testOnly *Hpack*'"
echo ""

# Run HPACK unit tests
echo "========================================"
echo "Running HPACK Unit Tests"
echo "========================================"
echo ""

cd "$(dirname "$0")/.."
sbt 'coreJVM/testOnly *Hpack*' 2>&1 | tail -30

echo ""
echo "========================================"
echo "Summary"
echo "========================================"
echo ""
echo "HPACK test vectors downloaded to: $VECTORS_DIR"
echo ""
echo "To add more comprehensive vector tests, create a test that:"
echo "  1. Parses JSON files from $VECTORS_DIR/<impl>/"
echo "  2. Feeds wire bytes to HpackDecoder"
echo "  3. Verifies decoded headers match expected"
echo "  4. Feeds headers to HpackEncoder"
echo "  5. Verifies encoded bytes decode correctly (round-trip)"
echo ""
